name: Build and deploy JAR app to Azure Web App - team28

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      id-token: write        # for azure/login
      contents: read         # for checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "microsoft"

      - name: Build with Maven
        run: mvn clean install

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4D034EBE93D74EE08B762B29D224C26C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5F394A65CC89481F96541B4C1CDED0F4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4CE6A6F8BC2A46D0AE00B74D9A2A99BB }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "team28"
          slot-name: "Production"
          package: "${{ github.workspace }}/target/*.jar"
